# -*- coding: utf-8 -*-
"""ProcTHOR-Tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Il6TqmRXOkzYMIEaOU9e4-uTDTIb5Q78

# Install AI2-THOR

ProcTHOR houses are loaded into `ai2thor` and distributed with the `prior` package. We'll also install a helper package, called `ai2thor_colab`, which allows us to run AI2-THOR in Google Colab.

Let's install each of these packages below:
"""

# Here, we'll install and use a pre-release of AI2-THOR.
!pip install --upgrade ai2thor --quiet
!pip install ai2thor-colab prior --upgrade &> /dev/null

"""# Download ProcTHOR-10k

Now, let's use the `prior` package to easily download the `procthor-10k` dataset:
"""

import prior

dataset = prior.load_dataset("procthor-10k")
dataset

"""ProcTHOR-10k comes with 3 splits, including:
- 10k `"train"` houses
- 1k `"val"` houses
- 1k `"test"` houses

these can be obtained by indexing into the dataset:
"""

dataset["train"]

"""Here is an example of how to load a single house's JSON file:"""

house = dataset["train"][0]
type(house), house.keys(), house

"""# Load a house into AI2-THOR

First, let's import in a Controller from AI2-THOR:
"""

from ai2thor.controller import Controller

"""To run AI2-THOR in Google Colab, we need to start an xserver, which allows us to load and observe images from the AI2-THOR Unity application, without having an external monitor or a GPU. Here, we'll use `ai2thor_colab`'s `start_xserver` function:"""

import ai2thor_colab
ai2thor_colab.start_xserver()

"""Let's now choose a ProcTHOR house we want to load into AI2-THOR:"""

house = dataset["train"][3]

"""And create a Controller that is initialized to that scene:"""

controller = Controller(scene=house)

"""# Egocentric Images

We now have an agent placed in the scene ready to execute actions! Let's check out what it's looking at:
"""

from PIL import Image

Image.fromarray(controller.last_event.frame)

"""# Navigation Actions

And take a few steps around:
"""

event = controller.step(action="RotateRight")
Image.fromarray(event.frame)

event = controller.step(action="RotateRight")
Image.fromarray(event.frame)

event = controller.step(action="LookUp")
Image.fromarray(event.frame)

event = controller.step(action="MoveAhead")
Image.fromarray(event.frame)

"""# Top-Down Frame

We can also get a top-down image of the frame:
"""

import copy

def get_top_down_frame():
    # Setup the top-down camera
    event = controller.step(action="GetMapViewCameraProperties", raise_for_failure=True)
    pose = copy.deepcopy(event.metadata["actionReturn"])

    bounds = event.metadata["sceneBounds"]["size"]
    max_bound = max(bounds["x"], bounds["z"])

    pose["fieldOfView"] = 50
    pose["position"]["y"] += 1.1 * max_bound
    pose["orthographic"] = False
    pose["farClippingPlane"] = 50
    del pose["orthographicSize"]

    # add the camera to the scene
    event = controller.step(
        action="AddThirdPartyCamera",
        **pose,
        skyboxColor="white",
        raise_for_failure=True,
    )
    top_down_frame = event.third_party_camera_frames[-1]
    return Image.fromarray(top_down_frame)


get_top_down_frame()

"""# Randomize the Agent's Position

To randomize the agent's position, we can get the set of grid positions that the agent can reach from 90 degree rotations and 0.25m separated movements. Here, we'll call `GetReachablePositions`:
"""

event = controller.step(action="GetReachablePositions")
event.metadata["actionReturn"]

"""And to visualize these positions, let's plot them on a scatter plot:"""

import matplotlib.pyplot as plt
reachable_positions = event.metadata["actionReturn"]
xs = [rp["x"] for rp in reachable_positions]
zs = [rp["z"] for rp in reachable_positions]

fig, ax = plt.subplots(1, 1)
ax.scatter(xs, zs)
ax.set_xlabel("$x$")
ax.set_ylabel("$z$")
ax.set_title("Reachable Positions in the Scene")
ax.set_aspect("equal")

"""Now, let's randomize the agent's position and rotation:"""

import random

position = random.choice(reachable_positions)
rotation = random.choice(range(360))
print("Teleporting the agent to", position, " with rotation", rotation)

event = controller.step(action="Teleport", position=position, rotation=rotation)

Image.fromarray(event.frame)

"""# Randomize Object Materials

To randomize the materials of objects, we can use the `RandomizeMaterials` function:
"""

fig, axs = plt.subplots(2, 5, figsize=(20, 8))

for ax in axs.flat:
    event = controller.step(action="RandomizeMaterials")
    ax.imshow(event.frame)
    ax.axis("off")

"""# Changing houses

To switch the agent to a different house, we can use AI2-THOR's `reset` method:
"""

new_house = dataset["train"][1]
controller.reset(scene=new_house)

get_top_down_frame()

"""# More Details

This notebook provided a very minimal demo to get started with ProcTHOR. More about ProcTHOR will be open-sourced and documented soon.

For more details about how to use AI2-THOR, please checkout the API references at [ai2thor.allenai.org](https://ai2thor.allenai.org).
"""