"""Relation sentences between object descriptions, and the key that caches them.

COMPONENT-OF-NODE: n08_semantic_edges  (NOT the node -- see below)

The deterministic half of SG2: pair enumeration, the cache key, the relation
prompt, and sentence validation. It writes none of the node's channels, so it
carries no IMPLEMENTS-NODE marker -- the structural check that compares a
node's declared writes against its source would otherwise pass on a file that
produces no edges at all.

The half that needs a GPU -- Qwen for the sentence, a frozen text encoder for
e_ij, and C2's bounded repair -- lives in ``semantic_edges_run.py``.

What the paper says
-------------------

Paper 2.5: "semantic edges are generated by prompting an LLM with object
descriptions to produce natural language relation sentences. These sentences
are then encoded into dense vectors using a frozen text encoder (e.g., CLIP or
BERT), resulting in edge embeddings e_ij".

Why no coordinates may enter the prompt
---------------------------------------

[L1-SEMEDGE-POS-INDEPENDENT] Appendix C proves SE(3) equivariance on the
premise that "these semantic edge embeddings are invariant to the input node
positions x, as they depend solely on object-level text descriptions". That is
a PREMISE, not something the implementation gets for free: the descriptions are
ours to build, and nothing stops a coordinate entering one. A prompt that
mentioned "the chair at (3.2, 0, 1.8)" would make e_ij a function of x and
quietly invalidate the proof the whole design rests on.

So the prompt takes two descriptions and nothing else. Not the distance between
the objects, not which is left of which, not the room. Spatial dependency is
already carried by the PHYSICAL edges; the semantic edge is the other half of
paper 2.3's dual-edge design, and mixing coordinates in would collapse them.

Why the key hashes descriptions rather than categories
------------------------------------------------------

[L1-SEMEDGE-KEY] An earlier draft keyed on (category_a, category_b), which
collapses "office chair + desk" and "dining chair + dining table" into one
relation. The key hashes both descriptions plus the prompt, LLM and encoder
versions, so a change to any of them invalidates the cache rather than serving
a stale sentence produced by a different pipeline.

MEASURED: over all 12,000 ProcTHOR houses this collapses 4,128,637 semantic
edges into 4,242 distinct description pairs -- a 99.90% cache hit rate. That is
a consequence of [U-12]: ProcTHOR's per-assetId metadata is category-level, so
every dining table shares a description. On a dataset with per-instance
descriptions the same key would collapse far less, which is the point of
hashing descriptions rather than categories.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Iterator

__all__ = [
    "PROMPT_VERSION",
    "MAX_ATTEMPTS",
    "SemanticEdgeError",
    "build_relation_prompt",
    "build_repair_prompt",
    "cache_key",
    "iter_pair_descriptions",
    "parse_sentence",
    "validate_sentence",
]

PROMPT_VERSION = 1
MAX_ATTEMPTS = 2  # C2's hard bound; the third outcome is a degraded edge

MAX_SENTENCE_CHARS = 300

# Anything that would make e_ij a function of world coordinates. Checked against
# the PROMPT, which we control, so this is a guard on our own code rather than
# an attempt to sanitise model output.
_COORDINATE_HINT = re.compile(
    r"\b(position|coordinate|x\s*=|y\s*=|z\s*=|metres away|meters away|"
    r"rotation|orientation|world.frame)\b",
    re.I,
)


class SemanticEdgeError(Exception):
    """A rejected relation sentence, carrying the message the repair prompt needs."""


def cache_key(desc_i: str, desc_j: str, prompt_version: int, llm_model: str,
              text_encoder_version: str) -> str:
    """[L1-SEMEDGE-KEY] sha256 over both descriptions and all three versions.

    The pair is sorted before hashing. relation(A, B) and relation(B, A) are the
    same undirected edge here ([U-19], our convention), and an unsorted key would
    silently double both the cache and the LLM bill.
    """
    a, b = sorted((desc_i, desc_j))
    payload = json.dumps([a, b, prompt_version, llm_model, text_encoder_version],
                         ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(payload.encode()).hexdigest()


def iter_pair_descriptions(graph: dict, text_map: dict) -> Iterator[tuple[tuple[int, int], str, str]]:
    """Every semantic-edge candidate n07 selected, as a pair of descriptions.

    Yields ``((i, j), desc_i, desc_j)``. Node INDICES travel alongside so a
    caller can attach the resulting embedding back to the right edge; they are
    deliberately not part of the cache key, since the same two descriptions in
    two different houses describe the same relation.
    """
    nodes = graph["nodes"]
    for i, j in graph["sem_edge_ids"]:
        ai, aj = str(nodes[i]["asset_id"]), str(nodes[j]["asset_id"])
        ti, tj = text_map.get(ai), text_map.get(aj)
        if ti is None or tj is None:
            raise KeyError(f"no object text for {ai if ti is None else aj}")
        yield (i, j), ti["text"], tj["text"]


def build_relation_prompt(desc_i: str, desc_j: str) -> str:
    """[L1-SEMEDGE-POS-INDEPENDENT] Two descriptions in, no geometry.

    The assertion at the end is not defensive programming against a caller
    mistake -- it guards the premise of Appendix C's proof against a future edit
    to this very function, which is exactly where a coordinate would get added
    by someone trying to make the sentences richer.
    """
    prompt = (
        "Two objects appear in the same indoor scene:\n"
        f"  A: {desc_i}\n"
        f"  B: {desc_j}\n"
        "\n"
        "Write ONE short sentence describing the functional or contextual "
        "relationship between them -- how they are typically used together, or "
        "why they belong in the same space. Examples of the KIND of relation "
        "wanted: \"a microscope is used on a lab bench\", \"a pillow rests on a "
        "bed\".\n"
        "\n"
        "Do not mention any positions, distances, directions or orientations. "
        "Describe the relationship only. Reply with the sentence alone."
    )
    assert not _COORDINATE_HINT.search(prompt), (
        "the relation prompt gained a spatial term; Appendix C's equivariance "
        "proof requires e_ij to depend solely on object descriptions"
    )
    return prompt


def build_repair_prompt(original: str, error: str, raw_response: str) -> str:
    """C2's retry. Must name the failure and differ from the original."""
    if not error:
        raise ValueError("a repair prompt with no error to repair is just a resend")
    return (
        f"{original}\n"
        "\n"
        "YOUR PREVIOUS ANSWER WAS REJECTED.\n"
        f"Reason: {error}\n"
        f"What you returned: {raw_response[:300]}\n"
        "\n"
        "Fix exactly that problem and reply with the corrected sentence alone."
    )


def parse_sentence(raw: str) -> str:
    """Strip the wrapping a chat model adds; keep the first sentence.

    Models answer "Sure! Here's a sentence: ..." however they like, and treating
    that as a content failure would spend a C2 attempt on formatting.
    """
    text = raw.strip()
    fenced = re.search(r"```(?:\w+)?\s*(.*?)```", text, re.S)
    if fenced:
        text = fenced.group(1).strip()
    # A leading "Sure, here is ...:" preamble, only when a colon precedes the
    # actual sentence on the same line.
    text = re.sub(r"^[^.\n]{0,60}:\s*", "", text, count=1)
    text = text.strip().strip('"').strip()
    first = text.split("\n", 1)[0].strip()
    return first


def validate_sentence(sentence: str) -> str:
    """[SG2 sg2_validate] Non-empty and encodable, with an actionable message."""
    s = sentence.strip()
    if not s:
        raise SemanticEdgeError("the response contained no sentence")
    if len(s) > MAX_SENTENCE_CHARS:
        raise SemanticEdgeError(
            f"the sentence is {len(s)} characters, over the {MAX_SENTENCE_CHARS} "
            "limit. Reply with one short sentence."
        )
    if not any(c.isalpha() for c in s):
        raise SemanticEdgeError("the sentence contains no words")
    return s


def load_text_map(path: Path) -> dict:
    return json.loads(path.read_text())
