"""Declare a real-model three-slot diagnostic, without inventing a paper scene."""
import hashlib
import json
from pathlib import Path
import shutil
import numpy as np

WORK = Path(__file__).resolve().parent
REPO = WORK.parents[2]
PARENT = WORK.parent / "stage1_cpu_real_20260908/data/outputs/checkpoints/actual_cpu_step/stage1_best_ckpt.json"
CHILD = WORK.parent / "stage2_cpu_real_20260908/data/outputs/variant_ckpts.json"
BASE_CACHE = WORK.parent / "stage2_cpu_real_20260908/data/outputs/sem_edge_cache.json"


def digest(path):
    with Path(path).open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def write(path, value):
    with path.open("x") as stream:
        stream.write(json.dumps(value, indent=2) + "\n")


def main():
    protocol_path = WORK.parent / "custom_table1_cpu_real_20260907/protocol/protocol.json"
    protocol = json.loads(protocol_path.read_text())
    ids = sorted(protocol["gallery_uids"])
    provenance = {"classification": "IMPLEMENTATION CHOICE: three explicitly hand-declared diagnostic slots and room; not generated by IDesign, not the author's Table2 scene list.",
                  "candidate_selection": "same six fixed Objaverse UIDs used in the preceding custom evaluator, sorted; not selected by score", "protocol": str(protocol_path), "protocol_sha256": digest(protocol_path)}
    texts, assets, queries, sources = {}, {}, [], {}
    raw = WORK / "raw_queries"
    raw.mkdir(exist_ok=False)
    for i, uid in enumerate(ids):
        rec = protocol["records"][uid]
        annotation_path = Path(rec["annotation"]["path"])
        annotation = json.loads(annotation_path.read_text())
        assert digest(annotation_path) == rec["annotation"]["sha256"]
        sources[str(annotation_path)] = digest(annotation_path)
        texts[uid] = {"text": rec["canonical_text"], "relation_text": annotation["description"]}
        mesh_path = Path(rec["mesh"]["path"])
        assert digest(mesh_path) == rec["mesh"]["sha256"]
        assets[uid] = {"mesh": {**rec["mesh"], "frame": "raw_gltf_y_up"}, "annotation": rec["annotation"]}
        if i < 3:
            x, y = ((1., 1.), (3., 1.), (2., 3.))[i]
            slot = {"new_object_id": f"diagnostic_slot_{i + 1}",
                    "position": {"x": x, "y": y, "z": .4},
                    "rotation": {"z_angle": (0., 90., 30.)[i]},
                    "size_in_meters": {"length": .8, "width": .8, "height": .8},
                    "placement": {"objects_in_room": []}}
            query = {"slot": slot, "text": annotation["description"]}
            if i == 1:
                image = annotation_path.parents[1] / "renders" / uid / "view_00.png"
                sources[str(image)] = digest(image)
                target = raw / f"{uid}_view_00.png"
                shutil.copy2(image, target)
                query["images"] = [str(target)]
            if i == 2:
                cloud = Path(rec["cloud"]["path"])
                assert digest(cloud) == rec["cloud"]["sha256"]
                sources[str(cloud)] = digest(cloud)
                target = raw / f"{uid}.npz"
                shutil.copy2(cloud, target)
                query["pointcloud"] = str(target)
            queries.append(query)
    room_id = "real-model-diagnostic-three-slots"
    request = {"schema": "metafind.scene_request.v1", "provenance": provenance,
               "stage1_record": str(PARENT), "stage2_record": str(CHILD), "variant": "full",
               "gallery_registry": str(WORK / "data/outputs/gallery_index.json"), "gallery_ids": "all",
               "asset_texts": str(WORK / "asset_texts.json"), "semantic_cache": str(BASE_CACHE),
               "initial_graph": {"room_id": room_id, "nodes": []}, "queries": queries,
               "mode": "iterative", "use_layout": True}
    room = {"room_id": room_id, "dimensions": [4., 4., 3.], "provenance": provenance,
            "surfaces": [{"id": "floor", "vertices": [[0.,0.,0.],[4.,0.,0.],[4.,4.,0.],[0.,4.,0.]],
                          "rgba": [.65,.65,.65,1.], "roughness": .7}]}
    eye, target = np.array([6., -7., 6.]), np.array([2., 2., .5])
    forward = target - eye
    forward /= np.linalg.norm(forward)
    right = np.cross(forward, [0.,0.,1.]); right /= np.linalg.norm(right)
    up = np.cross(right, forward)
    matrix = np.eye(4); matrix[:3,:3] = np.stack([right,up,-forward],axis=1); matrix[:3,3] = eye
    light = np.eye(4); light[:3,3] = [2.,2.,6.]
    render = {"provenance": provenance, "engine": "CYCLES", "device": "CPU", "threads": 2,
              "samples": 8, "seed": 20260908, "resolution": [512,512], "transparent": False,
              "world": {"color": [.5,.5,.5], "strength": .3},
              "color_management": {"view_transform": "Standard", "look": "None", "exposure": 0., "gamma": 1.},
              "cameras": [{"id": "diagnostic-perspective", "matrix_world": matrix.tolist(), "lens_mm": 42., "sensor_width_mm": 36., "clip_start": .01, "clip_end": 100.}],
              "lights": [{"id": "diagnostic-area", "type": "AREA", "shape": "DISK", "matrix_world": light.tolist(), "energy": 600., "color": [1.,1.,1.], "size": 4.}]}
    for filename, value in (("request_00.json",request),("asset_texts.json",texts),
                            ("assets.json",{"provenance":provenance,"assets":assets}),
                            ("room.json",room),("render.json",render),
                            ("raw_query_sources.json",sources)):
        write(WORK / filename,value)
    print(json.dumps({"queries":len(queries),"gallery":len(ids),"request":str(WORK/'request_00.json')}))


if __name__ == "__main__":
    main()
