#!/bin/bash
# n06 -> n09 -> Stage 1 smoke, each step gated on the last.
#
#   nohup bash tools/chain_to_stage1.sh > .../logs/chain2.log 2>&1 &
#
# Replaces chain_after_n05.sh, which queued n05 -> n08 -> Stage 1 and left out
# the two steps in between. n05 and n08 both finished; Stage 1 then stopped on a
# missing stage1_protocol.json, which n09 writes. The gate caught it -- the
# chain refused to continue rather than training on whatever it could find --
# but the plan was wrong before the gate had anything to catch.
#
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script incrementally
# by byte offset, so an edit mid-run shifts the offset and it resumes in the
# middle of a word. That is not hypothetical: editing the previous chain live
# produced `line 36: ath: command not found` and killed it.

set -uo pipefail

REPO=/home/kyzen/MetaFindV1
PY=$HOME/miniconda3/envs/MetaFind/bin/python
# Roots come from metafind/paths.py, never spelled here. Six scripts used
# to hardcode the previous machine's /mnt/data1/kyzen/MetaFind, so on any
# other checkout they silently observed an empty directory.
eval "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && ${METAFIND_PYTHON:-python3} -m metafind.paths)"
OUT="$METAFIND_OUTPUTS"
LOGS=$OUT/logs

cd "$REPO" || exit 1
mkdir -p "$LOGS"

say() { echo "[$(date '+%F %H:%M:%S')] $*"; }
curves() { $PY "$REPO/tools/plot_training.py" 2>&1 | sed 's/^/  /'; }

# `x=$(find ... | wc -l)` swallows find's exit status: the pipeline's status is
# wc's, which is 0 whatever find did, so a failed count still yields a plausible
# number and that number decides whether a chain runs. Any stderr from find is
# also a failure and not a warning -- one unreadable subdirectory makes find
# exit 0 with a SHORT count, and a short count at a gate kills a healthy run.
# Same shape as tools/run_ulip_full.sh:74-85, which already treats it this way.
# `-type f` so a DIRECTORY named *.json cannot count as an artifact.
count() {
    local n err rc
    err=$(mktemp) || return 1
    n=$(find -L "$@" -type f 2>"$err"); rc=$?
    if [ $rc -ne 0 ] || [ -s "$err" ]; then
        printf 'counting %s failed (rc=%s): %s\n' "$1" "$rc" "$(head -c 300 "$err")" >&2
        rm -f "$err"
        return 1
    fi
    rm -f "$err"
    printf '%s\n' "$n" | grep -c . || true
}

die() {
    say "STOPPED: $*"
    curves
    say "nothing after this point ran"
    exit 1
}

# Every prerequisite this chain assumes, checked ONCE up front rather than
# discovered one stage at a time. The previous chain found its missing input
# after n08 had already run for 22 minutes; the input was missing the whole
# time and could have been reported before anything started.
say "=== preflight ==="
for f in annotations/. procthor_modalities/. sem_edge_cache.json \
         stage1_encoding_protocol.json stage1_hyperparameters.json; do
    [ -e "$OUT/$f" ] || die "missing prerequisite: $OUT/$f"
done
# -L: $OUT/annotations is a symlink to /home/kyzen/metafind_out/annotations.
# Without it this counted 0 and the gate below killed the chain no matter how
# many annotations existed.
ANN=$(count "$OUT/annotations" -maxdepth 1 -name '*.json') \
    || die "could not count annotations -- see the error above"
say "annotations $ANN  ·  n08 artifacts present"
# The threshold is unchanged. Only the message: it named ~45,955, a previous
# corpus size, so a reader who hit this gate was told the wrong target.
# The braces matter: `wc -l < missing 2>/dev/null` does NOT suppress the
# error, because the redirect fails in the SHELL before wc starts, so the
# message is bash's and the 2>/dev/null attached to wc never sees it. The
# fallback still worked -- only the suppression was theatre.
N05_TARGET=$({ wc -l < "$LOGS/renders_index.jsonl"; } 2>/dev/null || echo '?')
[ "$ANN" -ge 45000 ] || die "only $ANN annotations; n04 indexed $N05_TARGET"

if pgrep -f "metafind\.(data|train)\." > /dev/null; then
    die "another metafind stage is already running; refusing to compete for the GPU"
fi

# ---------------------------------------------------------------------- n06
# Caches the FROZEN halves only. OpenCLIP does not move in Stage 1 (U-34), so
# recomputing text and image for 45,953 assets every epoch would be the same
# arithmetic every time. The point cloud is deliberately NOT cached -- PointBERT
# is in the optimizer, so a cached point embedding would be the output of a
# network that is about to change.
say "=== n06 encode text + image (frozen OpenCLIP) ==="
$PY -m metafind.data.encode_text_image >> "$LOGS/n06_full.log" 2>&1
rc=$?
[ $rc -eq 0 ] || die "n06 exited $rc -- read $LOGS/n06_full.log"

# -L, same defect as the annotation count above: $OUT/embeddings is a symlink
# to /home/kyzen/metafind_out/embeddings. The directory is still empty, so the
# difference is not measurable HERE -- it is measured on its sibling
# $OUT/annotations, identical construction, which reads 0 without -L and
# 38,849 with it. Once n06 writes its ~45,953 .npz this returned 0 and the
# gate below killed the chain immediately after a SUCCESSFUL n06.
EMB=$(count "$OUT/embeddings" -maxdepth 1 -name '*.npz') \
    || die "n06 returned 0 but its output could not be counted"
say "embeddings written: $EMB"
[ "$EMB" -ge 45000 ] || die "n06 returned 0 but wrote only $EMB embeddings"

# ---------------------------------------------------------------------- n09
say "=== n09 build splits + stage1 protocol ==="
$PY -m metafind.data.splits >> "$LOGS/n09_full.log" 2>&1
rc=$?
[ $rc -eq 0 ] || die "n09 exited $rc -- read $LOGS/n09_full.log"

for f in splits.json stage1_protocol.json; do
    [ -f "$OUT/$f" ] || die "n09 returned 0 but did not write $f"
done

# G3 dereferences this: the protocol names a hyperparameter artifact by hash,
# and Stage 1 refuses to start if the file on disk hashes differently. Checking
# here means the mismatch is reported before the 9.5 GB backbone is loaded.
$PY - <<'CHECK' || die "stage1_protocol does not match the hyperparameter artifact"
import json
from metafind import paths
tr = json.loads((paths.OUTPUTS / "stage1_protocol.json").read_text())
hp = json.loads((paths.OUTPUTS / "stage1_hyperparameters.json").read_text())
assert tr["hyperparameter_config_hash"] == hp["sha256"], (
    tr["hyperparameter_config_hash"][:12], hp["sha256"][:12])
sp = json.loads((paths.OUTPUTS / "splits.json").read_text())["object"]
print(f"  train {len(sp['train']):,}  test {len(sp['test']):,}  "
      f"config {hp['sha256'][:12]}")
CHECK

# ------------------------------------------------------------- Stage 1 smoke
# 200 assets, one epoch. Its job is to prove the P0 fixes hold against a REAL
# loaded backbone -- the checkpoint's point-encoder section, the full
# gallery-encoder hash, the ProcTHOR pc_norm -- none of which can be tested
# without the 9.5 GB of weights, which is why the audit marks them SPEC ONLY.
say "=== Stage 1 smoke: 200 assets, 1 epoch ==="
$PY -m metafind.train.stage1 --limit 200 --epochs 1 >> "$LOGS/n10_smoke.log" 2>&1
rc=$?
[ $rc -eq 0 ] || die "Stage 1 smoke exited $rc -- read $LOGS/n10_smoke.log"

$PY - <<'CHECK' || die "the checkpoint is missing something the optimizer moved"
import json, torch
from metafind import paths
from metafind.train.stage1 import CKPT_SECTIONS
ck = torch.load(paths.CHECKPOINTS / "stage1.pt", map_location="cpu", weights_only=False)
missing = [s for s in CKPT_SECTIONS if s not in ck]
assert not missing, missing
n = {s: sum(v.numel() for v in ck[s].values()) for s in CKPT_SECTIONS}
print("  " + "  ".join(f"{k.split('_')[0]}={v:,}" for k, v in n.items()))
# P0-1, stated as an assertion: the point encoder has to BE in the file.
assert n["backbone_trainable_state"] > 1_000_000, (
    f"backbone section holds only {n['backbone_trainable_state']:,} parameters "
    "-- PointBERT is not in the checkpoint")
rec = json.loads((paths.CHECKPOINTS / "stage1_ckpt.json").read_text())
print(f"  record: {rec['n_params_saved']:,} params, {rec['size_bytes']/1e6:.0f} MB")
CHECK

# A checkpoint that saved is not a run that learned. The curves are where that
# distinction is visible, so the loss is checked here rather than left to a
# reader who might not look.
$PY - <<'CHECK' || die "the smoke ran but the loss did not move"
import json
from metafind import paths
rows = [json.loads(l) for l in
        (paths.LOGS / "train_stage1.jsonl").read_text().splitlines() if l.strip()]
assert len(rows) >= 2, f"only {len(rows)} metric rows -- too few to say anything"
first, last = rows[0]["loss"], rows[-1]["loss"]
print(f"  loss {first:.4f} -> {last:.4f} over {len(rows)} logged steps")
# A smoke run on 200 assets is too short to demand convergence; what it CAN
# rule out is a loss that is constant, NaN, or diverging -- each of which means
# something is wired wrong rather than under-trained.
assert last == last, "loss is NaN"
assert last < first * 3, f"loss grew from {first:.4f} to {last:.4f}"
CHECK

curves
say "curves -> $OUT/training_curves.html"
say "=== n06, n09 and the Stage 1 smoke all finished and were verified ==="
say "next, and NOT automated: full Stage 1, then n11 gallery index"
